In [1]:
import numpy as np

def showarray(a, fmt='png'):
    a = np.uint8(a)
    f = StringIO()
    PIL.Image.fromarray(a).save(f, fmt)
    IPython.display.display(IPython.display.Image(data=f.getvalue()))
    
class GF():
    def __init__(self, f):
        Max = np.max(f)
        f2 = np.zeros(Max+1, np.uint8)
        f2[f] = 1
        f = np.flip(f2)
        self.len_of_symbol = Max
        self.q = 2**self.len_of_symbol
        self.table = np.array(self.make_code_table(f))
        
    def sub_matrix(self, A, i, j):
        A1 = np.delete(A, i, 0)
        A2 = np.delete(A1, j, 1)
        return A2

    def det(self, A):
        size = A.shape
        if size[0]==2 and size[1]==2:
            d = self.add(self.multi(A[0, 0],A[1, 1]), self.multi(A[1, 0],A[0, 1]))
            return d
        else:
            d = 0
            for i in range(size[0]):
                d=self.add(self.multi(A[0, i],self.det(self.sub_matrix(A, 0, i))), d)
            return d
        
    def make_code_table(self, f):
        m = len(f)-1
        N = 2**m
        table = ["0"*m]
        x =""
        for i in range(1,m+1):
            if f[i]==0:
                x+="0"
            else:
                x+="1"
        for i in range(0, m):
            c="0"*m
            c = c[0:i] + "1"+c[i+1:]
            c = c[::-1]
            table.append(c)
        for i in range(m+1, N):
            a = table[-1]
            a1 = a[1:]+"0"
            b = "0"*m
            if a[0]=="1":
                b = x
            c = self.add_string_code(a1, b)
            table.append(c)
        return table

    def add_string_code(self, a, b):
        c =""
        for i in range(self.len_of_symbol):
            if a[i]!= b[i] :
                c+="1"
            else:
                c+="0"
        return c
    def add(self, a, b):
        if  np.isscalar(a) and  np.isscalar(b):
            a= int(a)
            b = int(b)
            a1 = self.table[a]
            b1 = self.table[b]
            c1 = self.add_string_code(a1, b1)
            c, = np.where(self.table == c1)
            return c[0]
        elif not np.isscalar(a):
            if np.isscalar(b):
                raise ValueError("a, b must have same shape ( a:",a.shape,", b is scalar)" )
            else:
                a_size = a.shape
                b_size = b.shape
                if  len(a_size) ==2 and  len(a_size)==2:
                    if a_size[0] != b_size[0] or a_size[1] != b_size[1] :
                        raise ValueError("a, b must have same shape ( a:"+ str(a.shape) +",  b:"+str(b.shape)+ ")" )
                    else:
                        c = np.zeros_like(a, np.uint8)
                        for i in range(a_size[0]):
                            for j in range(a_size[1]):
                                c[i, j] = self.add(a[i, j], b[i, j])
                        return c
                elif len(a_size)==1 and len(b_size)==1 and a_size ==b_size :
                    c = np.zeros_like(a, np.uint8)
                    for i in range(a_size[0]):
                        c[i] = self.add(a[i], b[i])
                    return c
                else:
                    raise ValueError("a, b must have same shape ( a:"+ str(a.shape) +",  b:"+str(b.shape)+ ")" )         
    def multi(self, a, b):
        if  np.isscalar(a) and  np.isscalar(b):
                if a ==0 or b == 0:
                    return 0
                else:
                    c = (a+b-2) % (self.q-1)
                    return c+1
        elif not np.isscalar(a):
            a_size = a.shape
            if np.isscalar(b):
                c = [self.multi(i, b) for i in a]
                return np.array(c)
            b_size = b.shape
            if a_size[1] != b_size[0] :
                raise ValueError("Can not multiply 2 matrix of dimension: ", a.shape, b.shape)
            else:
                c = np.zeros((a_size[0], b_size[1]), np.uint8)
                for i in range(a_size[0]):
                    for j in range(b_size[1]):
                        for k in range(a_size[1]):
                            c[i, j] =self.add(c[i, j], self.multi(a[i, k], b[k, j])) 
                return c
    def make_sub_matrix(self, x):
        N =  N = self.q -1
        sub = np.zeros((N, N), np.uint8)
        index = x-1
        for i in range(N):
            sub[i, index] = index+1
            index +=1
            if index ==N:
                index =0
        return sub
    def reserve_e(self, a):
            a2 = self.q+1-a
            if a2 == self.q:
                a2 = 1
            if a2 == self.q+1:
                a2 = 0
            return a2
    def Reserve_fast(self, X, show =False):
        N = X.shape[0]
        def make_I(n):
                In = np.zeros((n, n), np.uint8)
                for i in range(n):
                    In[i, i] =1
                return In
        X1 = make_I(N)
        for i in range(N):
            if show:
                print(i)
            C = make_I(N)
            for j in range(N):
                C[j, i] = self.multi(X[j, i], self.reserve_e(X[i,i]))
            C[i,i] = self.reserve_e(X[i,i])
            X = self.multi(C,X)
            X1 = self.multi(C,X1)
        return X1
    
def Resever(X, gl32):
    A = X.copy()
    size= A.shape
    if size[0]!=size[1]:
        print("Maxtrix is not square!")
        return None
    E = np.zeros_like(A)
    for i in range(E.shape[0]):
        E[i, i] =1
        
    def process_row( i, Ax, Ex):
        A = Ax.copy()
        E = Ex.copy()
        for j in range(i):
            if A[i, j]!=0:
                x = gl32.reserve_e(A[i, j])
                A[i] = gl32.multi(A[i], x)
                E[i] = gl32.multi(E[i], x)
                A[i] = gl32.add(A[i], A[j])
                E[i] =  gl32.add(E[i],E[j])
                
        if A[i, i]>1:
            x = gl32.reserve_e(A[i, i])
            A[i] = gl32.multi(A[i], x)
            E[i] = gl32.multi(E[i], x)
        return A, E
            
    # Convert to up triangle matrix
    i = 0
    stt = 0
    while i < size[0]:
        A, E = process_row(i, A, E)
        stt+=1
        if A[i, i]==0:
            if stt>size[0]-i+1:
                print("matrix is not ivertable")
                return 0
            A[i:-1], A[-1] = A[i+1:].copy(), A[i].copy()
            E[i:-1], E[-1] = E[i+1:].copy(), E[i].copy()
        else:
            stt= 0
            i+=1
            
    # Convert to E
    for i in range(size[0]):
        for j in range(i+1, size[1]):
            if A[i, j]!=0:
                for x in range(32):
                    if gl32.multi(x, 1)==A[i, j]:
                        A[i] = gl32.add(A[i] , gl32.multi(A[j], x))
                        E[i] = gl32.add(E[i] , gl32.multi(E[j], x))
                        break

    return E

def Rank(Zx, gl32):
    Z = Zx.copy()
    index = []
    i =-1
    stt = -1
    while i <np.min(Zx.shape)-1 and Z.shape[0]>=np.min(Zx.shape):
        i+=1
        stt+=1
        for j in range(i):
            if Z[i, j]!=0:
                x = 0
                for k in range(32):
                    if gl32.multi(k, Z[i, j])==Z[j, j]:
                        x = k
                        break  
                Z[i] = gl32.multi(Z[i], x)
                Z[i] = gl32.add(Z[i], Z[j])
        ok = True
        if Z[i, i]==0:
            ok = False
            for j in range(i+1, G):
                if Z[i, j]!=0:
                    Z[:,i], Z[:, j] = Z[:, j].copy(), Z[:, i].copy()
                    ok = True
                    break
        if ok:
            index.append(stt)
        else:
            Z = np.delete(Z, i, 0)
            i-=1
    return len(index), index

In [8]:
gl32 = GF([3,  1, 0])
N = gl32.q-1

x = np.ones(N, np.uint8)
y = np.arange(1, N+1)
f0 = gl32.add(x, y)
Q = np.zeros((N, N), np.uint8)
Q[0] = f0.copy()
for i in range(1, N):
    Q[i] = np.roll(gl32.multi(Q[i-1], 2), 1)
    
    
N1 = 2
N2= 5


    
H_base = Q[:N1, N1:N2+N1]
print(Q)
print("#"*20)
print(H_base)
H = np.zeros((N1*N, N2*N), np.int16)
for i in range(N1):
    for j in range(N2):
        if H_base[i, j]!=0:
            sub_matrix = gl32.make_sub_matrix(H_base[i, j])
            H[i*N:(i+1)*N, j*N:(j+1)*N] = sub_matrix
print(H.shape)            
print(H)
H = H[0:13]
np.save("H.npy", H)

[[0 4 7 2 6 5 3]
 [4 0 5 1 3 7 6]
 [7 5 0 6 2 4 1]
 [2 1 6 0 7 3 5]
 [6 3 2 7 0 1 4]
 [5 7 4 3 1 0 2]
 [3 6 1 5 4 2 0]]
####################
[[7 2 6 5 3]
 [5 1 3 7 6]]
(14, 35)
[[0 0 0 0 0 0 7 0 2 0 0 0 0 0 0 0 0 0 0 6 0 0 0 0 0 5 0 0 0 0 3 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 6 0 0 0 0 4 0 0 0]
 [0 2 0 0 0 0 0 0 0 0 4 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 5 0 0]
 [0 0 3 0 0 0 0 0 0 0 0 5 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 6 0]
 [0 0 0 4 0 0 0 0 0 0 0 0 6 0 0 0 3 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 7]
 [0 0 0 0 5 0 0 0 0 0 0 0 0 7 0 0 0 4 0 0 0 0 0 3 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 6 0 1 0 0 0 0 0 0 0 0 0 0 5 0 0 0 0 0 4 0 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 5 0 0 1 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0 0 0 0 7 0 0 0 0 0 6 0]
 [0 0 0 0 0 6 0 0 2 0 0 0 0 0 0 0 0 4 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 7]
 [0 0 0 0 0 0 7 0 0 3 0 0 0 0 0 0 0 0 5 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 6 0 0 0 3 0 0 0 0 0 2 0 0 0 0 0]
 [0 2 0 0 0 0 0 0 0 

In [ ]:
gl32 = GF([3,  1, 0])
N = gl32.q-1

x = np.ones(N, np.uint8)
y = np.arange(1, N+1)
f0 = gl32.add(x, y)
Q = np.zeros((N, N), np.uint8)
Q[0] = f0.copy()
for i in range(1, N):
    Q[i] = np.roll(gl32.multi(Q[i-1], 2), 1)
    
    
N1 = 2
N2= 5


    
H_base = Q[:N1, N1:N2+N1]

print(H_base.shape)
H = np.zeros((N1*N, N2*N))
for i in range(N1):
    for j in range(N2):
        if H_base[i, j]!=0:
            sub_matrix = gl32.make_sub_matrix(H_base[i, j])
            H[i*N:(i+1)*N, j*N:(j+1)*N] = sub_matrix

def check_errors(Ht, min_cw):
    stt = 0
    for i in range(min_cw-1, Ht.shape[0]):
        for j in range(Ht.shape[1]+min_cw -1-i, Ht.shape[1]):
            if Ht[i, j]!=0:
                stt +=1
    print(min_cw-2, stt)
def savetxt(file, X):
    l =  2
    with open(file, 'w') as f:
        for row in X:
            for e in row:
                s = ""
                s = " " +str(int(e))+ "," if e <10 else str(int(e))+","
                f.write(s)
            f.write("\n")
            
H0 = H.copy()
m = 13
index = np.random.permutation(H.shape[0])
H = H[index[:m]].copy()
H0 = H.copy()
np.save("H.npy", H0)
shape = H.shape
def get_col_weight(hi):
    x = np.zeros_like(hi)
    x[hi!=0]=1
    return sum(x)

H2 = np.zeros((shape[0]+1, shape[1]))    
H2[-1] = np.arange(H.shape[1])
H2[:-1] = H.copy()
H= H2.copy()

for j in range(shape[1]-1):
    is_done = False
    if get_col_weight(H[:-1, j])==1:
        H[:,j], H[:, shape[1]-1] = H[:, shape[1]-1].copy(), H[:,j].copy()
        for k in range(m):
            if H[k, shape[1]-1]!=0:
                H[k], H[shape[0]-1] = H[shape[0]-1].copy(), H[k].copy()
                is_done= True
                break
    if is_done:
        break

for i in range(1, m):
    for j in range(shape[1]-1-i):
        is_done = False
        if get_col_weight(H[:-i, j])==1:
            H[:,j], H[:, shape[1]-1-i] = H[:, shape[1]-1-i].copy(), H[:,j].copy()
            for k in range(m-i):
                if H[k, shape[1]-1-i]!=0:
                    H[k], H[shape[0]-1-i] = H[shape[0]-1-i].copy(), H[k].copy()
                    is_done= True
                    break
        if is_done:
            break
sub = H[-1].copy()
H= H[:-1]
print(H)
savetxt("H.txt", H)
Ht=H.copy()

In [24]:
M = H.shape[0]
N = H.shape[1]
G = 0
print(M, N, G)
T = Ht[:M-G,N-M+G:]
print(T)
T2 = Resever(T, gl32)
E = Ht[M-G:,N-M+G:]

13 35 0
[[4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [4. 0. 6. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 6. 0. 0. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 5. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 2. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]
 [0. 0. 6. 0. 0. 0. 1. 0. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0. 6. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 3. 0. 2. 0. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4. 0. 0. 0. 3.]]


In [25]:
print(gl32.multi(T, T2))

[[1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [26]:
savetxt("Ht.txt",Ht.astype(np.uint8));
savetxt("T.txt",T.astype(np.uint8));
savetxt("E.txt",E.astype(np.uint8));

In [27]:
X = Ht[:M-G, :N+G-M]
Y = Ht[M-G:, :N+G-M]
savetxt("X.txt",X.astype(np.uint8));
savetxt("Y.txt",Y.astype(np.uint8));
ET2 = gl32.multi(E, T2)
print(ET2)
ET2XY  = gl32.add(gl32.multi(ET2, X), Y)

[]


In [28]:
Z = ET2XY.transpose().copy()
savetxt("Z.txt",Z.astype(np.uint8));
rank , index = Rank(Z, gl32)

In [29]:
print(index)

[]


In [30]:
Htd = Ht.copy()
Htd[:, N-M:N-M+G], Htd[:, index] = Ht[:, index], Ht[:, N-M:N-M+G]
savetxt("Htd.txt", Htd.astype(np.uint8));

In [31]:
A = Htd[:M-G,:N-M]
B = Htd[:M-G, N-M:N-M+G]
C = Htd[M-G:, :N-M]
D = Htd[M-G:, N-M:N-M+G]
# np.save("Htd.npy", Htd)
# np.save("A.npy", A)
# np.save("B.npy", B)
# np.save("T.npy", T)
# np.save("C.npy", C)
# np.save("D.npy", D)
# np.save("E.npy", E)

np.savetxt("D.txt",D.astype(np.uint8),fmt='%i', delimiter=',');

In [32]:
C2 =gl32.add(gl32.multi(gl32.multi(E, T2), A), C)
D2 =gl32.add(gl32.multi(gl32.multi(E, T2), B), D)
print(D2)
np.savetxt("D2.txt",D2.astype(np.uint8),fmt='%i', delimiter=',');
D3 = Resever(D2, gl32)
np.savetxt("D3.txt",D3.astype(np.uint8),fmt='%i', delimiter=',');
D3C2 = gl32.multi(D3, C2)
np.savetxt("D3C2.txt",D3C2.astype(np.uint8),fmt='%i', delimiter=',');

[]


In [33]:
BD3C2 = gl32.multi(B, D3C2)
ABD3C2 = gl32.add(A, BD3C2)
T2ABD3C2 = gl32.multi(T2,ABD3C2)

In [34]:
u = np.random.randint(0, gl32.q, H.shape[1] - H.shape[0]).reshape(N-M, 1)
p1 = gl32.multi(D3C2, u)
Au = gl32.multi(A, u)
Bp1 = gl32.multi(B, p1)
p2 = gl32.multi(T2, gl32.add(Au, Bp1))
print(y0)
y0 = np.concatenate((u, p1, p2))
y = np.zeros_like(y0)
y[sub.astype(np.uint8)] = y0
print(y)
print("#"*30)
print(gl32.multi(H0, y))

[[5]
 [6]
 [0]
 [1]
 [4]
 [0]
 [6]
 [2]
 [0]
 [6]
 [4]
 [7]
 [0]
 [1]
 [4]
 [0]
 [2]
 [5]
 [2]
 [6]
 [1]
 [4]
 [6]
 [1]
 [3]
 [1]
 [3]
 [1]
 [2]
 [1]
 [0]
 [4]
 [0]
 [1]
 [6]]
[[7]
 [4]
 [5]
 [2]
 [5]
 [6]
 [2]
 [3]
 [3]
 [2]
 [2]
 [0]
 [1]
 [4]
 [3]
 [4]
 [1]
 [1]
 [7]
 [6]
 [1]
 [5]
 [0]
 [1]
 [0]
 [5]
 [1]
 [7]
 [1]
 [2]
 [2]
 [7]
 [7]
 [2]
 [1]]
##############################
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [35]:
print(D3C2.shape)
print(T2ABD3C2.shape)
G = np.concatenate((D3C2, T2ABD3C2))
savetxt("G.txt", G)
p = gl32.multi(G, u)
y0 = np.concatenate((u, p))
y = np.zeros_like(y0)
y[sub.astype(np.uint8)] = y0
print(sub)
print(y)
print("#"*30)
print(gl32.multi(H0, y))

(0, 22)
(13, 22)
[25. 24. 34. 22. 27. 23.  6.  7.  8.  9. 10. 32. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21.  3.  5. 26. 28. 29.  4.  0. 30. 31.  1. 33. 11.  2.]
[[7]
 [4]
 [5]
 [2]
 [5]
 [6]
 [2]
 [3]
 [3]
 [2]
 [2]
 [0]
 [1]
 [4]
 [3]
 [4]
 [1]
 [1]
 [7]
 [6]
 [1]
 [5]
 [0]
 [1]
 [0]
 [5]
 [1]
 [7]
 [1]
 [2]
 [2]
 [7]
 [7]
 [2]
 [1]]
##############################
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [36]:
np.save("G.npy", G)
np.save("sub.npy", sub.astype(np.uint8))
np.save("H.npy", H0)

In [37]:
G2 = Resever(G, gl32)

Maxtrix is not square!


In [ ]:
for row in G:
    S = "("
    for e in row:
        S+=str(e)
        S+=", "
    S = S[:-2]
    S+="),"
    print(S)

In [ ]:
s = "("
for i in u:
    s+=str(i[0])+", "
s+=")"
print(s)

In [ ]:
pi = 0
stt = 0
for i in range(726):
    pi=gl32.add(pi, gl32.multi(u[i][0], G[stt,i]))
    print(u[i][0], G[stt,i], pi)

In [ ]:
print(p)

In [ ]:
def nhan_hang(A, i, a):
    K = np.zeros_like(A)
    for j in range(A.shape[0]):
        K[j, j] = a if j==i-1 else 1
    return K

def doi_hang(A, i, j):
    K = np.zeros_like(A)
    for k in range(A.shape[0]):
        K[k, k] = 1
    K[i-1, i-1] = 0
    K[j-1, j-1] = 0
    K[i-1, j-1]= 1
    K[j-1, i-1] = 1
    return K

def cong_hang(A, a, i, j):
    K = np.zeros_like(A)
    for k in range(A.shape[0]):
        K[k, k] = 1
    K[j-1, i-1] = a
    return K

In [ ]:
A = np.array([
    [2, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 2],
    [0, 1, 0, 2]
])
K1 = nhan_hang(A, 1, 31)
K = K1.copy()
A = gl32.multi(K1, A)
print(A)
print("#"*20)
K2 = cong_hang(A, 1, 2, 4)
K = gl32.multi(K2, K)
A = gl32.multi(K2, A)
print(A)
print("#"*20)
K3 = nhan_hang(A, 4, 31)
K = gl32.multi(K3, K)
A = gl32.multi(K3, A)
print(A)
print("#"*20)
K4 = cong_hang(A, 31, 3, 1)
K = gl32.multi(K4, K)
A = gl32.multi(K4, A)
print(A)
print("#"*20)
K5 = cong_hang(A, 1, 4, 1)
K = gl32.multi(K5, K)
A = gl32.multi(K5, A)
print(A)
print("#"*20)
K6 = cong_hang(A, 2, 4, 3)
K = gl32.multi(K6, K)
A = gl32.multi(K6, A)
print(A)
print("#"*20)


In [ ]:
A = np.array([
    [2, 0, 1, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 2],
    [0, 1, 0, 2]
])
A2 = gl32.multi(A, K)
print(K)
print(A2)

In [ ]:
print(gl32.table)

In [ ]:
print(gl32.add(2, 19))

In [ ]:
for a in range(32):
    print("#"*20)
    print(a)
    for i in range(32):
        for j in range(i+1, 32):
            if gl32.add(i,j)==a:
                print(i, "+", j)